### ISSUE TITLE
Default / example parser?

### ISSUE THREAD

**Issue by jbrechtel** [qfpl/waargonaut#49]
Would you be interested in a PR that included a few default parsing functions (similar to or exactly like https://github.com/qfpl/waargonaut/blob/master/test/Types/Common.hs#L255) along with docs related to them?

My team recently decided to try Waargonaut and it took us a little while to piece together what was needed to construct a parser and we thought we could help reduce that time for another team.

I'm asking because I'm not sure if this would seem to be stepping on the toes of "BYO parsing library" by suggesting a default implementation.

**Comment by mankyKitty** [comment]
Yay! Users!

I think there are two parts to this...

- More documentation is required for what it means to 'BYO parsing lib'
- Cater for a super simple 'happy path' that provides a `ByteString -> Either e a` function.

The former seems obvious, this issue exists, therefore I should expand on that topic. :+1: Would having more thorough documentation (with examples) let your team avoid this problem?

My thoughts on the latter tend to end up at either:
* Including a "reasonable default" parsing package with `waargonaut`
* Trivial `waargonaut-attoparsec`, `waargonaut-trifecta` type companion packages

We already use `attoparsec` in the test-suite so that wouldn't be a stretch, and `hw-json` uses it as well. That's a rather long winded way of saying that I would be interested in such a PR. :)

**Comment by mankyKitty** [comment]
The decoding and parsing integration is being overhauled as part of #60 so this should be less of an issue now. I'll close this unless others feel strongly about it.
